// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCihVZ48CE5LfpkcSHpfdOpjzWglbb6Dy4',
    appId: '1:343204336259:web:a67797d05d44ab2e4041b6',
    messagingSenderId: '343204336259',
    projectId: 'smartwallet-c97fe',
    authDomain: 'smartwallet-c97fe.firebaseapp.com',
    storageBucket: 'smartwallet-c97fe.firebasestorage.app',
    measurementId: 'G-KJSJTPTSEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDES-OF1FzMAfEXnCMKIM2oNecfCZSE2vs',
    appId: '1:343204336259:android:542ba57af87ddc5b4041b6',
    messagingSenderId: '343204336259',
    projectId: 'smartwallet-c97fe',
    storageBucket: 'smartwallet-c97fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8cNPmzx_O4sZqgEAkvk85OHHQz-FjEHE',
    appId: '1:343204336259:ios:0b36b37f1f883db14041b6',
    messagingSenderId: '343204336259',
    projectId: 'smartwallet-c97fe',
    storageBucket: 'smartwallet-c97fe.firebasestorage.app',
    iosClientId: '343204336259-nt9hgnba1rsk302a5qhogvlpnlu9vcn4.apps.googleusercontent.com',
    iosBundleId: 'com.mobilewallet.v1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8cNPmzx_O4sZqgEAkvk85OHHQz-FjEHE',
    appId: '1:343204336259:ios:0b36b37f1f883db14041b6',
    messagingSenderId: '343204336259',
    projectId: 'smartwallet-c97fe',
    storageBucket: 'smartwallet-c97fe.firebasestorage.app',
    iosClientId: '343204336259-nt9hgnba1rsk302a5qhogvlpnlu9vcn4.apps.googleusercontent.com',
    iosBundleId: 'com.mobilewallet.v1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCihVZ48CE5LfpkcSHpfdOpjzWglbb6Dy4',
    appId: '1:343204336259:web:f852a41568d960054041b6',
    messagingSenderId: '343204336259',
    projectId: 'smartwallet-c97fe',
    authDomain: 'smartwallet-c97fe.firebaseapp.com',
    storageBucket: 'smartwallet-c97fe.firebasestorage.app',
    measurementId: 'G-HSWXV2BHMN',
  );
}
